### ISSUE TITLE
顺序错了……

### ISSUE THREAD

**Issue by wby238** [padeoe/nju-lib-downloader#1]
页码根本对不上……
看了下调用，发现gs传入的顺序是错误的……
OS：x64 ubuntu 16.04

**Comment by wby238** [comment]
顺便还有这个错误：
```cmd
14:03:19.072 [main] DEBUG c.i.i.s.ByteBufferRandomAccessSource - class com.itextpdf.io.source.ByteBufferRandomAccessSource$1 cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @47eaca72
```

**Comment by wby238** [comment]
win下的错误：
```cmd
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.itextpdf.io.source.ByteBufferRandomAcc
essSource$1 (file:/xxxx/libpdf.jar) to method java.nio.DirectByt
eBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.itextpdf.io.so
urce.ByteBufferRandomAccessSource$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflect
ive access operations
WARNING: All illegal access operations will be denied in a future release
02:25:54.913 [main] DEBUG c.i.i.s.ByteBufferRandomAccessSource - class com.itext
pdf.io.source.ByteBufferRandomAccessSource$1 cannot access class jdk.internal.re
f.Cleaner (in module java.base) because module java.base does not export jdk.int
ernal.ref to unnamed module @3349e9bb
```
win7抓到的顺序正确。

**Comment by padeoe** [comment]
两个报错好像没影响。具体页码顺序错误我暂未重现

**Comment by padeoe** [comment]
已修复该bug，感谢反馈！

**Comment by wby238** [comment]
还是这个错误，ubuntu x64下载还是顺序乱了……用的是openjdk-8

-----
另外，win7下也出错了：
```log
java.nio.charset.MalformedInputException: Input length = 1
        at java.base/java.nio.charset.CoderResult.throwException(Unknown Source)

        at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
        at java.base/sun.nio.cs.StreamDecoder.read(Unknown Source)
        at java.base/java.io.InputStreamReader.read(Unknown Source)
        at java.base/java.io.BufferedReader.fill(Unknown Source)
        at java.base/java.io.BufferedReader.readLine(Unknown Source)
        at java.base/java.io.BufferedReader.readLine(Unknown Source)
        at java.base/java.nio.file.Files.readAllLines(Unknown Source)
        at com.sslibrary.object.InfoReader.read(InfoReader.java:38)
        at com.sslibrary.spider.BookDownloader.handleOldDir(BookDownloader.java:
539)
        at com.sslibrary.spider.BookDownloader.downloadFromMkdir(BookDownloader.
java:478)
        at com.sslibrary.spider.BookDownloader.downloadAllImages(BookDownloader.
java:617)
        at Starter.main(Starter.java:42)
开始下载 Book{id='11176655', name='STL源码剖析', author='侯捷', press='华中科技
大学出版社', publishDate='2002年06月第1版', theme='null', bookClass=all, detailB
ookClass='null'}
494/494    WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.itextpdf.io.source.ByteBufferRandomAcc
essSource$1 (file:/F:/学习用图书/libpdf.jar) to method java.nio.DirectByteBuffer
.cleaner()
WARNING: Please consider reporting this to the maintainers of com.itextpdf.io.so
urce.ByteBufferRandomAccessSource$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflect
ive access operations
WARNING: All illegal access operations will be denied in a future release
01:38:11.041 [main] DEBUG c.i.i.s.ByteBufferRandomAccessSource - class com.itext
pdf.io.source.ByteBufferRandomAccessSource$1 cannot access class jdk.internal.re
f.Cleaner (in module java.base) because module java.base does not export jdk.int
ernal.ref to unnamed module @44a7bfbc
```
```
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```
两个都是超星包库的

**Comment by padeoe** [comment]
emmm，我上次只修复了书香中国的乱序，忘记修复超星的。已经修复了，另外应该也不会报错了。我没有纯的Ubuntu环境暂时没测试，不过windows下测试通过。感谢！
