### ISSUE TITLE
下载完后，pdf文件只有0kb。不知道出什么问题。

### ISSUE THREAD

**Issue by zhihuo01** [padeoe/nju-lib-downloader#22]
java -jar libpdf-0.2.11-jar-with-dependencies.jar -t 8 "http://img.sslibrary.com/n/slib/book/slib/13257718/19cc8289703a417c8677f68ef51cc3b0/96b13d51906946f754fc67cb06b45e68.shtml?dxbaoku=true&deptid=323&fav=http%3A%2F%2Fwww.sslibrary.com%2Freader%2Fpdg%2Fdxpdgreader%3Fd%3Db79444f0676ac0cdc7b861e8ec2b1481%26enc%3Da6ea49cc4106d4b1bd0cf5401721af48%26ssid%3D13257718%26did%3D323%26username%3Ddx2baoku_112.93.141.210_323&fenlei=160517&spage=1&srh=1&t=5&username=dx2baoku_112.93.141.210_323&view=-1"
开始下载 Book{id='13257718', name='方剂学', author='贾波，李冀主编', press='中国中医药出版社', publishDate='2011.06', theme='null', bookClass=all, detailBookClass='null'}
217/217    java.lang.NullPointerException
        at com.sslibrary.spider.PDFGenerator.addOutline(PDFGenerator.java:71)
        at com.sslibrary.spider.PDFGenerator.addBookMark(PDFGenerator.java:62)
        at com.sslibrary.spider.BookDownloader.downloadBook(BookDownloader.java:662)
        at Starter.run(Starter.java:47)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at Starter.main(Starter.java:24)

**Comment by DertahSama** [comment]
我也是这样，应该是超星改了目录的语法，导致目录添加失败了
推销一下我新写的脚本，能正确处理出来~
