### ISSUE TITLE
超星cookies? 书香域名？

### ISSUE THREAD

**Issue by yygcom** [padeoe/nju-lib-downloader#4]
1 我的网络环境不是校园网，我打开超星的pdf时候需要先登录图书馆系统，然后查到书后连接到超星去，然后超星pdf貌似不限制ip，但图片的会限制cookies，能否加入cookies选项，可以使用手动从浏览器导出来的cookies文件呢？
2 书香的域名前缀个地方不一样，我用这个下载我这边的时候提示域名不对，手动改前缀后可以，能否加入域名自动识别呢？

**Comment by padeoe** [comment]
1由于我没有账号，不好测试尚未支持。2应该支持的呀，能把提示域名不对的输出给我看看吗

**Comment by padeoe** [comment]
2由于我统一把书的id提取并从书香清华下载的，可能有的书在别的站有，书香清华没有？

**Comment by yygcom** [comment]
书香那个今天没有遇到域名报错了，不知道是怎么回事。
另外，昨天也遇到的就是合并书香的pdf最后会报一段错误，虽然已经合并成功pdf了
错误代码如下：
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: ????.pdf
        at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
        at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
        at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
        at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
        at cn.chineseall.Downloader.mergePDF(Downloader.java:328)
        at cn.chineseall.Downloader.downloadandMerge(Downloader.java:229)
        at cn.chineseall.Downloader.downloadBookFromMkdir(Downloader.java:213)
        at cn.chineseall.Downloader.downloadBook(Downloader.java:187)
        at Starter.main(Starter.java:35)
???????69?

**Comment by yygcom** [comment]
cookie那个就好比wget 有一个 --cookie 参数可以将外部cookie文件作为http请求的cookie ，看看能不能加呢，可能你那边网络环境是ip就能访问所以不需要cookie
