### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by NT5182** [padeoe/nju-lib-downloader#8]
PS D:\> java -jar libpdf.jar -t 8 http://www.chineseall.cn/v3/book/detail/Hpayj
java.lang.NullPointerException
        at cn.chineseall.CoreService.getCookie(CoreService.java:70)
        at cn.chineseall.CoreService.getSession(CoreService.java:25)
        at cn.chineseall.Downloader.viewBookPageWeb(Downloader.java:174)
        at cn.chineseall.Downloader.initBookPara(Downloader.java:126)
        at cn.chineseall.Downloader.downloadBook(Downloader.java:182)
        at Starter.run(Starter.java:40)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at Starter.main(Starter.java:24)

**Comment by NT5182** [comment]
您好，我在使用的过程中遇到这个问题，能不能麻烦解决一下，万分感谢！

**Comment by padeoe** [comment]
你好，这是因为你的ip可能被服务器墙了，导致cookie获取失败

**Comment by padeoe** [comment]
建议换用新ip后把线程数量设置为1，频繁下载会被服务器封禁。我写好了一个配置http代理的版本，近期更新一下代码

**Comment by NT5182** [comment]
我知道了，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"padeoe"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月23日(星期天) 中午11:14
收件人:&nbsp;"padeoe/nju-lib-downloader"<nju-lib-downloader@noreply.github.com&gt;;
抄送:&nbsp;"Alex"<1731877332@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [padeoe/nju-lib-downloader] java.lang.NullPointerException (#8)




建议换用新ip后把线程数量设置为1，频繁下载会被服务器封禁。我写好了一个配置http代理的版本，近期更新一下代码
